### ISSUE TITLE
query parser

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#9]
use the parser for the crawled stuff!!!
should do the same thing..

**Comment by brianignacio5** [comment]
1. [ ] Query Parser: Parse the inserted query ( Some normalization needed?)
2. [ ] Free text query checker: Check if returned documents are lower than K docs, try different substrings combination of inserted query.

Moved this functionality to query parser since doesn't really concern ranker, but free text query checker could be another thing.

**Comment by moritzschaefer** [comment]
This goes into milestone 2 as well and we will discuss it after our first running version.
